---
version: 1

build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

ansible_config: 'ansible.cfg'
