---
name: Docker Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t ansible-ee context/

      - name: Verify Ansible is accessible in the built image.
        run: docker run --rm --name test-container ansible-ee ansible --version

      - name: Verify Ansible Runner is accessible in the built image.
        run: docker run --rm --name test-container ansible-ee ansible-runner --version

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Login to DockerHub.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: context/
          file: context/Dockerfile
          platforms: linux/amd64
          push: true
          tags: timgrt/ansible-anwendertreffen-demo-ee:latest
